version: "3.8"

services:
  mongo:
    image: mongo:8.0.12
    container_name: mongo_job_bot
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
